### ISSUE TITLE
client support multiple documents

### ISSUE THREAD

**Issue by smcoll** [novafloss/pydocusign#66]
This is a requirement for #65

**Comment by moiseshiraldo** [comment]
I've modified the client to add support for creating an envelope with multiple documents. Sorry if someone was working on it, but it's a small change and I thought it wouldn't worth to ask.

I've been working on the DocuSign integration at my company lately, so I would be glad to help if there's anything else I can do.

**Comment by zebuline** [comment]
fixed by #73
