### ISSUE TITLE
requireAcknowledgment attribute misspelled

### ISSUE THREAD

**Issue by smcoll** [novafloss/pydocusign#67]
it is spelled incorrectly as `requireAcknowledgment` when it should be `requireAcknowledgment`.  PR incoming.

**Comment by smcoll** [comment]
This was a typo when i first discovered it, but now it really bit me.  By default, the event notification configuration does not require acknowledgement, so there's no way to set this on an envelope without the attribute spelled correctly.  For accounts without a Connect configuration created, a Connect message which returns a non-200 will not be logged as a failure and retried, unless this fix is merged.

**Comment by zebuline** [comment]
fixed by #68
