### ISSUE TITLE
feature request: add or remove recipients to/from existing envelope

### ISSUE THREAD

**Issue by smcoll** [novafloss/pydocusign#70]
Recipients can be added until the envelope is complete, although auto emails will only be sent if the new recipient's routing order hasn't already been reached: https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Add%20Recipients%20to%20an%20Envelope.htm

Recipients whose process has not been completed can be removed: https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Delete%20Recipients%20from%20an%20Envelope.htm

i intend to make a PR for this soon.

**Comment by kbussell** [comment]
I started on this a little while back. Feel free to use it as a starting point if you wish: https://github.com/kbussell/pydocusign/commit/462bc9d8b03a656d0765213eb137b05fb793df81, or if it works for you, I can clean it up and submit it as a PR.

**Comment by smcoll** [comment]
@kbussell since this is an API client, i'm in favor of supporting add, remove, and update.  What is the thought behind an `UpdatedSigner` class rather than using an existing class?

As it turns out, the `PUT` method is a "create or update", so the same logic would handlel both cases.  Not sure how to make that intuitive in the client.

**Comment by kbussell** [comment]
I created a separate class because the data members were a subset of those available when creating the envelope. There are other ways of handling this, but the general style of these classes are very light on validation, so I just created another.

**Comment by zebuline** [comment]
fixed by #93
