### ISSUE TITLE
Refactor `DocuSignObject` to simplify creation and extension of objects

### ISSUE THREAD

**Issue by kbussell** [novafloss/pydocusign#74]
Issues I've run into when adding support for more DocuSign features and functionality:
- Defining the attributes multiple times (in the attribute list and in the constructor) is overly verbose
- Doctests for testing object serialization clutters up the code (this is more of a stylistic preference, but I tend to reserve doctests for cases where the the tests would be useful as documentation) 
- Had to create my own duplicate hierarchy of Tab objects when adding support for anchor strings

**Comment by zebuline** [comment]
Fixed by #75
