### ISSUE TITLE
feature request: Authentication via OAuth2 and acting on behalf of other users

### ISSUE THREAD

**Issue by kbussell** [novafloss/pydocusign#76]
See the documentation at: [OAuth2 Authentication Support](https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#OAuth2/OAuth2 Authentication Support in DocuSign REST API.htm) and [Acting As Other Account Users](https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#OAuth2/Acting As Other Account Users.htm)

(I am working on a PR for this.)

**Comment by zebuline** [comment]
fixed by #77
