### ISSUE TITLE
[Release] 1.0

### ISSUE THREAD

**Issue by zebuline** [novafloss/pydocusign#92]
Release the 1.0 version.

PR to include:

* [x] #89 
* [x] #93
* [x] #95

**Comment by zebuline** [comment]
@smcoll @kbussell as main external contributors, do you want to include other must-have features in this release ?

**Comment by kbussell** [comment]
I'd like to resolve the add/update/remove signers from envelope issue before sealing off 1.0 if that's ok. I'll create a PR with my version and we can figure out which we want to go with.

**Comment by kbussell** [comment]
Also for your consideration, see #94.

**Comment by smcoll** [comment]
i prefer @kbussell's #93 over #72; for one, it already has tests, and aside from the `add_envelope_recipient` (singular) convenience method, handles all the functionality in my PR plus some.

**Comment by zebuline** [comment]
@kbussell #94 added to th elist
@smcoll ok for me, #72 replaced by #93

**Comment by zebuline** [comment]
Done !
Thanks @kbussell and @smcoll

**Comment by kbussell** [comment]
🎉 Congrats on 1.0!
